# Copyright (c) 2018-2021 Simply Code Ltd. All rights reserved.
# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

version: "2"
checks:
  method-lines:
    enabled: true
    config:
      threshold: 100
plugins:
  csslint:
    enabled: true
    checks:
      order-alphabetical:
        enabled: false
  eslint:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD009:
        enabled: false
      MD013:
        enabled: false
      MD033:
        enabled: false
exclude_patterns:
- "**/Views/"
- "**/test/"
