# Copyright (c) 2018-2021 Simply Code Ltd. All rights reserved.
# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

sudo: required
dist: bionic
language: csharp
solution: hik-client.sln

addons:
  apt:
    packages:
      - doxygen
  sonarcloud:
    organization: simplycodeuk

mono:
  - latest

dotnet: 5.0

env:
  global:
    - ASPNETCORE_ENVIRONMENT=Development
    - DOTNET_PRINT_TELEMETRY_MESSAGE=false
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
  matrix:
    - CONFIG=Release
    - CONFIG=Debug

before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.22.*
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

cache:
  yarn: yes

install:
  - nuget restore hik-client.sln
  - dotnet --version
  - dotnet restore hik-client.sln

script:
  - doxygen ./docs/doxygen
  - sonar-scanner
  - dotnet build hik-client/src/hik-client.csproj       -c $CONFIG /p:DocumentationFile=codedoc.xml
  - dotnet build hik-client/test/hik-client.Test.csproj -c $CONFIG /p:DocumentationFile=codedoc.xml
  - dotnet build hikUI/src/hikUI.csproj                 -c $CONFIG /p:DocumentationFile=codedoc.xml
  - dotnet build hikUI/test/hikUI.Test.csproj           -c $CONFIG /p:DocumentationFile=codedoc.xml
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:ExcludeFromCoverage="**/*.cshtml" hik-client/test/hik-client.Test.csproj -c $CONFIG --logger:trx
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:ExcludeFromCoverage="**/*.cshtml" hikUI/test/hikUI.Test.csproj           -c $CONFIG --logger:trx

# Pipe the coverage data to Code Climate
after_script:
  - ./cc-test-reporter format-coverage -t lcov -o ./coverage/codeclimate.hik-client.json ./hik-client/test/coverage.info
  - ./cc-test-reporter format-coverage -t lcov -o ./coverage/codeclimate.hikUI.json ./hikUI/test/coverage.info
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 4
  - ./cc-test-reporter upload-coverage
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r ./hik-client/test/coverage.info
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r ./hikUI/test/coverage.info
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) final

notifications:
  slack: simplycodeuk:FZI8WzeengkGv5LI7WQSCrJs
