version: 2.1

workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - build:
          matrix:
            parameters:
              config: ["Debug", "Release"]

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    parameters:
      config:
        default: "Debug"
        type: string
    executor: win/default
    steps:
      - checkout
      - run:
          name: "Nuget Restore"
          command: nuget restore hik-client.sln
      - run:
          name: "dotnet version"
          command: dotnet --version
      - run:
          name: "Restore solution"
          command: dotnet restore hik-client.sln
      - run:
          name: "Build solution"
          command: dotnet build hik-client.sln -c << parameters.config >> /p:DocumentationFile=codedoc.xml
      - run:
          name: "Pack the solution"
          command: dotnet pack hik-client.sln -c << parameters.config >> 
      - run:
          name: "Test solution"
          command: dotnet test hik-client.sln -c << parameters.config >> /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeFromCoverage="**/*.cshtml" --logger:trx --results-directory:test_coverage --collect:"Code Coverage"
      - store_test_results:
          path: ./test_coverage
      - store_artifacts:
          path: ./test_coverage
      - run:
          name: "Publish the solution"
          command: dotnet publish hik-client.sln -c << parameters.config >>
